## Detection Of Phishing Websites using Machine Learning

## Importing Libraries

In [25]:
import pandas as pd
import numpy as np
import seaborn as sns


## Loading and reading the dataset

In [26]:
data = pd.read_csv('phishing.csv')

#displaying the first 10 rows
data.head(5)


Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0  graphicriver.net        0        0           1          1            0   
1         ecnavi.jp        0        0           1          1            1   
2      hubpages.com        0        0           1          1            0   
3   extratorrent.cc        0        0           1          3            0   
4     icicibank.com        0        0           1          3            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           0            1           1   
1             0        0              0           0            1           1   
2             0        0              0           0            1           0   
3             0        0              0           0            1           0   
4             0        0              0           0            1           0   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       0           0            1             0      0  
1           1       0           0            1             0      0  
2           1       0           0            1             0      0  
3           1       0           0            1             0      0  
4           1       0           0            1             0      0

In [4]:

data.head(10).T

0          1             2                3  \
Domain         graphicriver.net  ecnavi.jp  hubpages.com  extratorrent.cc   
Have_IP                       0          0             0                0   
Have_At                       0          0             0                0   
URL_Length                    1          1             1                1   
URL_Depth                     1          1             1                3   
Redirection                   0          1             0                0   
https_Domain                  0          0             0                0   
TinyURL                       0          0             0                0   
Prefix/Suffix                 0          0             0                0   
DNS_Record                    0          0             0                0   
Web_Traffic                   1          1             1                1   
Domain_Age                    1          1             0                0   
Domain_End                    1          1             1                1   
iFrame                        0          0             0                0   
Mouse_Over                    0          0             0                0   
Right_Click                   1          1             1                1   
Web_Forwards                  0          0             0                0   
Label                         0          0             0                0   

                           4           5                6               7  \
Domain         icicibank.com  nypost.com  kienthuc.net.vn  thenextweb.com   
Have_IP                    0           0                0               0   
Have_At                    0           0                0               0   
URL_Length                 1           1                1               1   
URL_Depth                  3           4                2               6   
Redirection                0           0                0               0   
https_Domain               0           0                0               0   
TinyURL                    0           1                0               0   
Prefix/Suffix              0           0                0               0   
DNS_Record                 0           0                1               0   
Web_Traffic                1           1                1               1   
Domain_Age                 0           1                1               0   
Domain_End                 1           1                1               0   
iFrame                     0           0                0               0   
Mouse_Over                 0           0                0               0   
Right_Click                1           1                1               1   
Web_Forwards               0           0                0               0   
Label                      0           0                0               0   

                        8                9  
Domain         tobogo.net  akhbarelyom.com  
Have_IP                 0                0  
Have_At                 0                0  
URL_Length              1                1  
URL_Depth               2                5  
Redirection             0                0  
https_Domain            0                0  
TinyURL                 0                0  
Prefix/Suffix           0                0  
DNS_Record              0                0  
Web_Traffic             1                1  
Domain_Age              0                0  
Domain_End              0                1  
iFrame                  0                0  
Mouse_Over              0                0  
Right_Click             1                1  
Web_Forwards            0                0  
Label                   0                0

In [6]:
#Displaying a summary of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Domain         10000 non-null  object
 1   Have_IP        10000 non-null  int64 
 2   Have_At        10000 non-null  int64 
 3   URL_Length     10000 non-null  int64 
 4   URL_Depth      10000 non-null  int64 
 5   Redirection    10000 non-null  int64 
 6   https_Domain   10000 non-null  int64 
 7   TinyURL        10000 non-null  int64 
 8   Prefix/Suffix  10000 non-null  int64 
 9   DNS_Record     10000 non-null  int64 
 10  Web_Traffic    10000 non-null  int64 
 11  Domain_Age     10000 non-null  int64 
 12  Domain_End     10000 non-null  int64 
 13  iFrame         10000 non-null  int64 
 14  Mouse_Over     10000 non-null  int64 
 15  Right_Click    10000 non-null  int64 
 16  Web_Forwards   10000 non-null  int64 
 17  Label          10000 non-null  int64 
dtypes: int64(17), object(1)
mem

## Data Preprocessing 
Here, we clean the data by applying data preprocesssing techniques and transform the data to use it in the models.

In [7]:
#Displaying a stastical summary of the dataset
data.describe()

Have_IP       Have_At    URL_Length     URL_Depth   Redirection  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       0.005500      0.022600      0.773400      3.072000      0.013500   
std        0.073961      0.148632      0.418653      2.128631      0.115408   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      1.000000      2.000000      0.000000   
50%        0.000000      0.000000      1.000000      3.000000      0.000000   
75%        0.000000      0.000000      1.000000      4.000000      0.000000   
max        1.000000      1.000000      1.000000     20.000000      1.000000   

       https_Domain       TinyURL  Prefix/Suffix    DNS_Record   Web_Traffic  \
count  10000.000000  10000.000000   10000.000000  10000.000000  10000.000000   
mean       0.000200      0.090300       0.093200      0.100800      0.845700   
std        0.014141      0.286625       0.290727      0.301079      0.361254   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      1.000000   
50%        0.000000      0.000000       0.000000      0.000000      1.000000   
75%        0.000000      0.000000       0.000000      0.000000      1.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

         Domain_Age  Domain_End        iFrame   Mouse_Over  Right_Click  \
count  10000.000000  10000.0000  10000.000000  10000.00000  10000.00000   
mean       0.413700      0.8099      0.090900      0.06660      0.99930   
std        0.492521      0.3924      0.287481      0.24934      0.02645   
min        0.000000      0.0000      0.000000      0.00000      0.00000   
25%        0.000000      1.0000      0.000000      0.00000      1.00000   
50%        0.000000      1.0000      0.000000      0.00000      1.00000   
75%        1.000000      1.0000      0.000000      0.00000      1.00000   
max        1.000000      1.0000      1.000000      1.00000      1.00000   

       Web_Forwards         Label  
count  10000.000000  10000.000000  
mean       0.105300      0.500000  
std        0.306955      0.500025  
min        0.000000      0.000000  
25%        0.000000      0.000000  
50%        0.000000      0.500000  
75%        0.000000      1.000000  
max        1.000000      1.000000

The above obtained result shows that the most of the data is made of 0's & 1's except 'Domain' & 'URL_Depth' columns. The Domain column doesnt have any significance to the machine learning model training. This resulted in the decision to drop the  *'Domain'* column from the dataset. 

In [27]:
#Dropping the Domain column
data = data.drop(['Domain'], axis = 1).copy()

This leaves the dataset with 16 features & a target column.

In [9]:
#Counting and checking for null values
data.isnull().sum()

Have_IP          0
Have_At          0
URL_Length       0
URL_Depth        0
Redirection      0
https_Domain     0
TinyURL          0
Prefix/Suffix    0
DNS_Record       0
Web_Traffic      0
Domain_Age       0
Domain_End       0
iFrame           0
Mouse_Over       0
Right_Click      0
Web_Forwards     0
Label            0
dtype: int64

To have the same range of feature values while splitting the data into training & testing sets, we need to shuffle the data

In [10]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          6            0             0   
1        0        0           1          2            0             0   
2        0        0           1          5            0             0   
3        0        0           0          0            0             0   
4        0        0           0          0            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           0           0   
1        0              0           0            1           0           1   
2        0              0           0            1           1           1   
3        0              0           0            0           0           0   
4        0              0           0            1           1           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0       0           0            1             0      1  
1       0           0            1             0      0  
2       0           0            1             0      1  
3       0           0            1             0      1  
4       0           0            1             0      1

## Training and Testing

In [20]:
from sklearn.model_selection import train_test_split
import sklearn.linear_model as lm
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

In [21]:
# Sepratating & assigning features and target columns to X & y
y = data['Label']
X = data.drop('Label',axis=1)

In [22]:
# Splitting the dataset into train and test sets: 80-20 split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2, random_state = 12)

## Machine Learning Models

From the dataset above, We have learnt that this is a supervised machine learning.
This dataset uses a  classification problem,  it has input URL classified as phishing (1) or legitimate (0).
The supervised machine learning models (classification) considered to train the dataset in this notebook are:
    
* LogisticRegression
* Decision Tree Classifiers
* Random Forest Classifiers
* XGBoost
* KNeighbors Classifier

In [18]:
# Creating holders to store the model performance results
ML_Model = []
acc_train = []
acc_test = []

#function to call for storing the results
def storeResults(model, a,b):
  ML_Model.append(model)
  acc_train.append(round(a, 3))
  acc_test.append(round(b, 3))

## LOGISTIC REGRESSION

In [23]:
# instantiate the model 
model = LogisticRegression(max_iter=1000)
# fit the model 
model.fit(X_train,np.ravel(y_train,order='C'))
#predicting the target value from the model for the samples
y_predict= model.predict(X_test)
y_train_model = model.predict(X_train)
y_test_model = model.predict(X_test)
model_score=model.score(X_test, y_test)

**Performance Evaluation:**

In [24]:
#computing the accuracy of the model performance
acc_train_model = accuracy_score(y_train,y_train_model)
acc_test_model = accuracy_score(y_test,y_test_model)

print("LogisticRegression: Accuracy on the Model: ",model_score)
print("LogisticRegression: Accuracy on training Data: {:.3f}".format(acc_train_model))
print("LogisticRegression: Accuracy on test Data: {:.3f}".format(acc_test_model))
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

LogisticRegression: Accuracy on the Model:  0.797
LogisticRegression: Accuracy on training Data: 0.805
LogisticRegression: Accuracy on test Data: 0.797
              precision    recall  f1-score   support

           0       0.73      0.94      0.82      1004
           1       0.92      0.65      0.76       996

    accuracy                           0.80      2000
   macro avg       0.82      0.80      0.79      2000
weighted avg       0.82      0.80      0.79      2000

[[944  60]
 [346 650]]


In [39]:
#storing the results. The below mentioned order of parameter passing is important.
#Caution: Execute only once to avoid duplications.
storeResults('LogisticRegression', acc_train_model, acc_test_model)

## Decision Tree Classifier

In [63]:
from sklearn.tree import DecisionTreeClassifier

# instantiate the model 
tree = DecisionTreeClassifier(max_depth = 5)
# fit the model 
tree.fit(X_train, y_train)
#predicting the target value from the model for the samples
y_test_tree = tree.predict(X_test)
y_train_tree = tree.predict(X_train)

tree_score=model.score(X_test, y_test)

**Performance Evaluation:**

In [64]:
#computing the accuracy of the model performance
acc_train_tree = accuracy_score(y_train,y_train_tree)
acc_test_tree = accuracy_score(y_test,y_test_tree)

print("Decision Tree: Accuracy on the Model: ",tree_score)
print("Decision Tree: Accuracy on training Data: {:.3f}".format(acc_train_tree))
print("Decision Tree: Accuracy on test Data: {:.3f}".format(acc_test_tree))
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

Decision Tree: Accuracy on the Model:  0.8005
Decision Tree: Accuracy on training Data: 0.814
Decision Tree: Accuracy on test Data: 0.811
              precision    recall  f1-score   support

           0       0.73      0.95      0.83      1011
           1       0.92      0.65      0.76       989

    accuracy                           0.80      2000
   macro avg       0.83      0.80      0.80      2000
weighted avg       0.83      0.80      0.80      2000

[[958  53]
 [346 643]]


In [43]:
#storing the results. The below mentioned order of parameter passing is important.
#Caution: Execute only once to avoid duplications.
storeResults('Decision Tree', acc_train_tree, acc_test_tree)

## Random Forest Classifier

In [44]:
# instantiate the model
forest = RandomForestClassifier(max_depth=5)
# fit the model 
forest.fit(X_train, y_train)
#predicting the target value from the model for the samples
y_test_forest = forest.predict(X_test)
y_train_forest = forest.predict(X_train)
model_score=model.score(X_test, y_test)

**Performance Evaluation:**

In [45]:
#computing the accuracy of the model performance
acc_train_forest = accuracy_score(y_train,y_train_forest)
acc_test_forest = accuracy_score(y_test,y_test_forest)

print("Random forest: Accuracy on the Model: ",model_score)
print("Random forest: Accuracy on training Data: {:.3f}".format(acc_train_forest))
print("Random forest: Accuracy on test Data: {:.3f}".format(acc_test_forest))
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

Random forest: Accuracy on the Model:  0.8005
Random forest: Accuracy on training Data: 0.819
Random forest: Accuracy on test Data: 0.818
              precision    recall  f1-score   support

           0       0.73      0.95      0.83      1011
           1       0.92      0.65      0.76       989

    accuracy                           0.80      2000
   macro avg       0.83      0.80      0.80      2000
weighted avg       0.83      0.80      0.80      2000

[[958  53]
 [346 643]]


In [47]:
#storing the results. The below mentioned order of parameter passing is important.
#Caution: Execute only once to avoid duplications.
storeResults('Random forest', acc_train_forest, acc_test_forest)

## KNeighborsClassifier

In [48]:
# instantiate the model
knn = KNeighborsClassifier(n_neighbors =1)
# fit the model 
knn.fit(X_train,np.ravel(y_train,order='C'))
#predicting the target value from the model for the samples
y_predict= knn.predict(X_test)

#predicting the target value from the model for the samples
y_test_knn = knn.predict(X_test)
y_train_knn = knn.predict(X_train)
model_score=knn.score(X_test, y_test)

**Performance Evaluation:**

In [49]:
#computing the accuracy of the model performance
acc_train_knn = accuracy_score(y_train,y_train_knn)
acc_test_knn = accuracy_score(y_test,y_test_knn)

print("KNeighborsClassifier: Accuracy on the Model: ",model_score)
print("KNeighborsClassifier: Accuracy on training Data: {:.3f}".format(acc_train_knn))
print("KNeighborsClassifier: Accuracy on test Data: {:.3f}".format(acc_test_knn))
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

KNeighborsClassifier: Accuracy on the Model:  0.805
KNeighborsClassifier: Accuracy on training Data: 0.816
KNeighborsClassifier: Accuracy on test Data: 0.805
              precision    recall  f1-score   support

           0       0.79      0.83      0.81      1011
           1       0.82      0.78      0.80       989

    accuracy                           0.81      2000
   macro avg       0.81      0.80      0.80      2000
weighted avg       0.81      0.81      0.80      2000

[[840 171]
 [219 770]]


In [51]:
#storing the results. The below mentioned order of parameter passing is important.
#Caution: Execute only once to avoid duplications.
storeResults('KNeighborsClassifier', acc_train_knn, acc_test_knn)

## XGBoost Classifier

In [52]:
# instantiate the model
xgb = XGBClassifier(use_label_encoder =False,learning_rate=0.4,max_depth=7)
#fit the model
xgb.fit(X_train, y_train)
#predicting the target value from the model for the samples
y_test_xgb = xgb.predict(X_test)
y_train_xgb = xgb.predict(X_train)
model_score=xgb.score(X_test, y_test)

[20:11:25] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


**Performance Evaluation:**

In [53]:
#computing the accuracy of the model performance
acc_train_xgb = accuracy_score(y_train,y_train_xgb)
acc_test_xgb = accuracy_score(y_test,y_test_xgb)

print("XGBoost: Accuracy on the Model: ",model_score)
print("XGBoost: Accuracy on training Data: {:.3f}".format(acc_train_xgb))
print("XGBoost : Accuracy on test Data: {:.3f}".format(acc_test_xgb))
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

XGBoost: Accuracy on the Model:  0.857
XGBoost: Accuracy on training Data: 0.869
XGBoost : Accuracy on test Data: 0.857
              precision    recall  f1-score   support

           0       0.79      0.83      0.81      1011
           1       0.82      0.78      0.80       989

    accuracy                           0.81      2000
   macro avg       0.81      0.80      0.80      2000
weighted avg       0.81      0.81      0.80      2000

[[840 171]
 [219 770]]


In [55]:
#storing the results. The below mentioned order of parameter passing is important.
#Caution: Execute only once to avoid duplications.
storeResults('XGBoost', acc_train_xgb, acc_test_xgb)

## Comparision of Models
To compare the models performance, a dataframe is created. The columns of this dataframe are the lists created to store the results of the model.

In [56]:
#creating dataframe
results = pd.DataFrame({ 'ML Model': ML_Model,    
    'Train Accuracy': acc_train,
    'Test Accuracy': acc_test})
results

ML Model  Train Accuracy  Test Accuracy
0    LogisticRegression           0.805          0.800
1         Decision Tree           0.814          0.812
2         Random forest           0.819          0.818
3  KNeighborsClassifier           0.816          0.805
4               XGBoost           0.868          0.857

In [57]:
#Sorting the datafram on accuracy
results.sort_values(by=['Test Accuracy', 'Train Accuracy'], ascending=False)

ML Model  Train Accuracy  Test Accuracy
4               XGBoost           0.868          0.857
2         Random forest           0.819          0.818
1         Decision Tree           0.814          0.812
3  KNeighborsClassifier           0.816          0.805
0    LogisticRegression           0.805          0.800

From the above comparision, it is clear that the XGBoost Classifier works well with this dataset. and can be used to further study the problem